export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  DASHBOARD: "/dashboard",
  PROFILEPAGE: "/profile-page",
  VERIFYOTP: "/verify-otp",
  RESET_PASSWORD: "/reset-password",
  FORGOTPASSWORD: "/forgot-password",
  PACKAGES: "/packages",
  PACKAGE_DETAILS: "/packages/:id",
  WITHDRAW: "/withdraw",
  REFERRALS: "/referrals",
  WITHDRAWAL_HISTORY: "/withdrawal-history",
  DEPOSIT_HISTORY: "/deposit-history",
  SETTINGS: "/settings",
  MEDICAL_INVESTMENT: "/investments/medical",
  PROPERTY_INVESTMENT: "/investments/property",
  TRADING_INVESTMENT: "/investments/trading",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_REQUESTS: "/admin/requests",
  ADMIN_PAYMENTS: "/admin/payments",
};